[icon]
globs = []
dirs  = []
files = []
exts  = []
conds = [
	{ if = "dir", text = "ðŸ“‚" },
	{ if = "!dir", text = "  " }
]

[filetype]
rules = [
	{ name = "*/", fg = "blue" },
	{ name = "*", fg = "white" }
]
