theme = "oktheme"

[editor]
line-number = "relative"
rulers = [80, 120]
bufferline = "multiple"
scroll-lines = 1
idle-timeout = 50
popup-border = "all"
cursorline = true
cursorcolumn = true
scrolloff = 0

[editor.statusline]
# left = ["mode", "spinner", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]
# separator = "â”‚"
left = []
center = []
right = []
separator = ""
mode.normal = "ğŸš€ NORMAL"
mode.insert = "ğŸ“ INSERT"
mode.select = "ğŸŒŸ SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = false
wrap-indicator = ""
wrap-at-text-width = true

[keys.normal]
# move/copy line below/above
"A-j" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
"A-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
"A-J" = [ "extend_to_line_bounds", "yank", "paste_after" ]
"A-K" = [ "extend_to_line_bounds", "yank", "paste_before" ]
"C-j" = "page_cursor_half_down"
"C-k" = "page_cursor_half_up"

# previous/next buffer
H = "goto_previous_buffer"
L = "goto_next_buffer"
x = "select_line_below"
X = "select_line_above"
C-p = "signature_help"

[keys.insert]
C-p = "signature_help"

[keys.normal.g]
E = "goto_file_end"

[keys.select.g]
E = "goto_file_end"
